name: 'ZC Cards'
description: 'Installs Zoocha Cards Component'
type: 'Feature'
recipes:
  - zr-media-bundle
  - zr-layout-builder-bundle
  - zr-paragraph-bundle
install:
  - linkit
config:
  strict: false
